name: varviz3d
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - python=3.10
  
  # Web frameworks
  - streamlit>=1.48
  - fastapi>=0.116
  - flask>=3.1
  - flask-cors>=6.0
  - uvicorn>=0.35
  
  # Data processing
  - pandas>=2.3
  - numpy>=2.1
  - requests>=2.32
  - aiohttp>=3.12
  
  # Bioinformatics
  - biopython>=1.85
  - biothings_client>=0.4
  - pyvcf3>=1.0
  
  # Visualization
  - plotly>=6.2
  - altair>=5.5
  - pillow>=11.3
  
  # Utilities
  - lxml>=5.3
  - pyyaml>=6.0
  - python-dotenv>=1.1
  - pydantic>=2.11
  - rich>=14.1
  
  # Development tools
  - watchdog>=6.0
  
  # Pip packages not in conda
  - pip
  - pip:
      - myvariant==1.0.0
      - requests-cache>=1.2